### ISSUE TITLE
"Key" parameter from?

### ISSUE THREAD

**Issue by ghost** [henry-richard7/Spotify-Account-Generator#1]
Hello,
where do you obtain the "key" parameter that is sent in the payload?

**Comment by henry-richard7** [comment]
Hey,
 To get the request parameters you have to use packet capture tool.
 For Android use HttpCanary (Available in Playstore) It needs root you can use Android Emulator with Root
 For ios use fiddler [Follow This](https://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/ConfigureForiOS)

**Comment by ghost** [comment]
Thanks for the reply. Is this parameter dynamic or static?

**Comment by henry-richard7** [comment]
The key might change after months or so
