### ISSUE TITLE
review

### ISSUE THREAD

**Issue by sadminnp** [henry-richard7/Spotify-Account-Generator#2]
not working make proxy-based account creator and please included requirement txt file

**Comment by henry-richard7** [comment]
hey thanks for your suggestion i am already working on proxy

**Comment by sadminnp** [comment]
thanks and make unlimited account creator

**Comment by henry-richard7** [comment]
The program is working fine though!

**Comment by sadminnp** [comment]
but it does not  auto verify email

**Comment by henry-richard7** [comment]
If you see at the right side it gives you the link to verify the account you could go to that link provided to verify the account

**Comment by sadminnp** [comment]
manually doing is bad than getting auto

**Comment by henry-richard7** [comment]
well i don't know how to do it but i will try that later thanks for the suggestion though i will try it!
