### ISSUE TITLE
Double click doesnt start

### ISSUE THREAD

**Issue by Vejas04** [henry-richard7/Spotify-Account-Generator#3]
Hello,
im very new to python but on the other scripts it worked well for me but here it doesnt.
When i double click the script a cmd window appears and closes instantly.
Regards

**Comment by henry-richard7** [comment]
Hey,
Check if you have install the following packages 
exrex
requests
PySimpleGUI
Faker

If not install then using pip
eg: pip install exrex

**Comment by Vejas04** [comment]
Thank you very much :)
Is there are also a way to confirm the accounts automatically somehow?
King Regards

**Comment by henry-richard7** [comment]
I am trying to implement that in next version!

**Comment by Vejas04** [comment]
All right! Thank you very much.
I think you can make a donation link or something in the future :)
King Regards

**Comment by henry-richard7** [comment]
Okay thank you for your suggestion!
