### ISSUE TITLE
Auto confirmation for eMail?

### ISSUE THREAD

**Issue by Vejas04** [henry-richard7/Spotify-Account-Generator#4]
Hello im once again here.
Could you make an auto confirmation for the eMail that the accounts would stay "safe".
I also would make a payment of 20 € for making this happening.
Thank you!
Have a nice day

**Comment by Vejas04** [comment]
Maybe this could help you somehow:
https://towardsdatascience.com/email-automation-with-python-72c6da5eef52
Regards

**Comment by henry-richard7** [comment]
okay i will take a look and thanks

**Comment by Vejas04** [comment]
Thank you very much 🥇 
Have a nice weekend.

**Comment by henry-richard7** [comment]
Hey,
 I have added auto verification please check it out

**Comment by Vejas04** [comment]
Hello,
thank you so much! Do you have discord or telegram or something where we can communicate faster? Because i have some questions. (Discord: Vejas#7154)
Regards

**Comment by henry-richard7** [comment]
Hey my discord id: Eyepatch_007#5373

**Comment by henry-richard7** [comment]
Also my telegram https://t.me/eyepatch_ghoul_7
