### ISSUE TITLE
Stoped working yesterday

### ISSUE THREAD

**Issue by jlaf2020** [henry-richard7/Spotify-Account-Generator#5]
I loved your work on the new version, i was using and testing for educational reasons, but until last night, when we press generate button, the terminal window only shows as 320 value, repeated the number of times that we set the amount of accounts to generate. Any ideias about what happend ?

Thanks and keep the excelent work !!!

**Comment by henry-richard7** [comment]
Can you provide me a screenshot?

**Comment by jlaf2020** [comment]
strange, i tested now outside rdp or virtual machine and worked again...
i'm going to investigate further and give you a reply.

Thanks

Em qua., 14 de out. de 2020 às 13:18, Henry Richard J <
notifications@github.com> escreveu:

**Comment by henry-richard7** [comment]
Well i think it happens because it makes too many requests for verifying the account so i should add proxy when verifying the accounts

**Comment by jlaf2020** [comment]
I was using a VPN to use the script maybe was that

Em qua, 14 de out de 2020 13:22, Henry Richard J <notifications@github.com>
escreveu:

**Comment by henry-richard7** [comment]
Yea maybe... if you run into any problem please update me.

**Comment by jlaf2020** [comment]
I made some adjustments in the code to it click on the received email on a
personal domain to validate the Spotify email, do you have interest in the
code? If so I can send to you

Em qua, 14 de out de 2020 13:25, Henry Richard J <notifications@github.com>
escreveu:

**Comment by henry-richard7** [comment]
okay send me it will help me a lot .

**Comment by jlaf2020** [comment]
Sorry i was to send the modified file to you and forget. I'll send asap

**Comment by henry-richard7** [comment]
ok i will wait

**Comment by jlaf2020** [comment]
Sorry to have taken so long to reply...


Em dom., 18 de out. de 2020 às 23:51, Henry Richard J <
notifications@github.com> escreveu:

**Comment by jlaf2020** [comment]
i find out whats the problem sometimes with the code, it's an error
generated by requests when the response
site has a invalid ssl certificate. I worked out doing the following :

import requestsfrom urllib3.exceptions import InsecureRequestWarning
# Suppress only the single warning from urllib3 needed.
requests.packages.urllib3.disable_warnings(category=InsecureRequestWarning)
# Set `verify=False` on
`requests.post`.requests.post(url='https://example.com',
data={'bar':'baz'}, verify=False)

Hope it helps, now i can use the script on VPS....


Em seg., 19 de out. de 2020 às 00:24, joao luiz aranha de faria <
joaoluizaranha@gmail.com> escreveu:

**Comment by henry-richard7** [comment]
Okay thanks a lot I will update by code!
